import { CalendarDay, Language } from './types';

export const CALENDAR_DATA: CalendarDay[] = [
  { ramadanDay: 1, date: '2026-02-18', weekday: 'Wednesday', suhoor: '05:53', iftar: '18:16' },
  { ramadanDay: 2, date: '2026-02-19', weekday: 'Thursday', suhoor: '05:51', iftar: '18:17' },
  { ramadanDay: 3, date: '2026-02-20', weekday: 'Friday', suhoor: '05:50', iftar: '18:18' },
  { ramadanDay: 4, date: '2026-02-21', weekday: 'Saturday', suhoor: '05:49', iftar: '18:19' },
  { ramadanDay: 5, date: '2026-02-22', weekday: 'Sunday', suhoor: '05:47', iftar: '18:20' },
  { ramadanDay: 6, date: '2026-02-23', weekday: 'Monday', suhoor: '05:46', iftar: '18:22' },
  { ramadanDay: 7, date: '2026-02-24', weekday: 'Tuesday', suhoor: '05:44', iftar: '18:23' },
  { ramadanDay: 8, date: '2026-02-25', weekday: 'Wednesday', suhoor: '05:43', iftar: '18:24' },
  { ramadanDay: 9, date: '2026-02-26', weekday: 'Thursday', suhoor: '05:41', iftar: '18:25' },
  { ramadanDay: 10, date: '2026-02-27', weekday: 'Friday', suhoor: '05:40', iftar: '18:26' },
  { ramadanDay: 11, date: '2026-02-28', weekday: 'Saturday', suhoor: '05:38', iftar: '18:28' },
  { ramadanDay: 12, date: '2026-03-01', weekday: 'Sunday', suhoor: '05:37', iftar: '18:29' },
  { ramadanDay: 13, date: '2026-03-02', weekday: 'Monday', suhoor: '05:35', iftar: '18:30' },
  { ramadanDay: 14, date: '2026-03-03', weekday: 'Tuesday', suhoor: '05:34', iftar: '18:31' },
  { ramadanDay: 15, date: '2026-03-04', weekday: 'Wednesday', suhoor: '05:32', iftar: '18:32' },
  { ramadanDay: 16, date: '2026-03-05', weekday: 'Thursday', suhoor: '05:31', iftar: '18:33' },
  { ramadanDay: 17, date: '2026-03-06', weekday: 'Friday', suhoor: '05:29', iftar: '18:34' },
  { ramadanDay: 18, date: '2026-03-07', weekday: 'Saturday', suhoor: '05:27', iftar: '18:36' },
  { ramadanDay: 19, date: '2026-03-08', weekday: 'Sunday', suhoor: '05:26', iftar: '18:37' },
  { ramadanDay: 20, date: '2026-03-09', weekday: 'Monday', suhoor: '05:24', iftar: '18:38' },
  { ramadanDay: 21, date: '2026-03-10', weekday: 'Tuesday', suhoor: '05:22', iftar: '18:39' },
  { ramadanDay: 22, date: '2026-03-11', weekday: 'Wednesday', suhoor: '05:22', iftar: '18:39' },
  { ramadanDay: 23, date: '2026-03-12', weekday: 'Thursday', suhoor: '05:21', iftar: '18:40' },
  { ramadanDay: 24, date: '2026-03-13', weekday: 'Friday', suhoor: '05:17', iftar: '18:42' },
  { ramadanDay: 25, date: '2026-03-14', weekday: 'Saturday', suhoor: '05:16', iftar: '18:43' },
  { ramadanDay: 26, date: '2026-03-15', weekday: 'Sunday', suhoor: '05:14', iftar: '18:45' },
  { ramadanDay: 27, date: '2026-03-16', weekday: 'Monday', suhoor: '05:12', iftar: '18:46' },
  { ramadanDay: 28, date: '2026-03-17', weekday: 'Tuesday', suhoor: '05:10', iftar: '18:47' },
  { ramadanDay: 29, date: '2026-03-18', weekday: 'Wednesday', suhoor: '05:08', iftar: '18:48' },
  { ramadanDay: 30, date: '2026-03-19', weekday: 'Thursday', suhoor: '05:07', iftar: '18:49' },
];

export const TRANSLATIONS: Record<Language, any> = {
  [Language.EN]: {
    title: "Mesquita Hazrat Hamza (R.A) - Schedule",
    subTitle: "Porto Muslim Cultural Center",
    suhoor: "Suhoor",
    iftar: "Iftar",
    ramadanMonth: "Ramadan",
    daysRemaining: "Days\nRemaining",
    save: "Save",
    cancel: "Cancel",
    iftarAlarm: "Iftar Adhan",
    suhoorAlarm: "Suhoor Alert",
    today: "Today",
    suhoorVoiceMsg: "Suhoor time has ended.",
    volume: "Volume",
    currentTimeLabel: "Current Time",
    voiceMale: "Male Voice",
    alarmsBtn: "Alarms",
    fullCalendar: "Full Calendar",
    close: "Close",
    ramadanDay: "Ramadan Day",
    date: "Date",
    ashra1: "10 Days of Mercy",
    ashra2: "10 Days of Blessing",
    ashra3: "10 Days of Forgiveness",
    ongoing: "Active",
    iftarRemaining: "Iftar in",
    suhoorRemaining: "Suhoor in",
    suhoorEnded: "Suhoor ended",
    iftarEnded: "Iftar ended",
    previewSuhoor: "Preview Suhoor Voice",
    share: "Share",
    shareMessage: "Date: {date}\n{day}\nSuhoor: {suhoor}\nIftar: {iftar}\nMesquita Hazrat Hamza (R.A)",
    copied: "Copied!",
    hadith: "Narrated Abu Huraira: The Prophet said, \"(Allah said), 'Every good deed of Adam's son is for him except fasting; it is for Me. and I shall reward (the fasting person) for it.' Verily, the smell of the mouth of a fasting person is better to Allah than the smell of musk.\" (Sahih al-Bukhari 5927)",
    periods: {
      dawn: "Dawn", morning: "Morning", noon: "Noon", afternoon: "Afternoon", evening: "Evening", night: "Night"
    },
    weekdays: {
      Monday: 'Monday', Tuesday: 'Tuesday', Wednesday: 'Wednesday', Thursday: 'Thursday',
      Friday: 'Friday', Saturday: 'Saturday', Sunday: 'Sunday'
    },
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
  },
  [Language.BN]: {
    title: "মসজিদ হযরত হামজা (রা:) - সময়সূচী",
    subTitle: "পোর্তো মুসলিম কালচারাল সেন্টার",
    suhoor: "সেহরি",
    iftar: "ইফতার",
    ramadanMonth: "রমজান",
    daysRemaining: "রোজার আর\nবাকি আছে",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    iftarAlarm: "ইফতার আজান",
    suhoorAlarm: "সেহরি অ্যালার্ট",
    today: "আজকে",
    suhoorVoiceMsg: "সেহরির সময় শেষ হয়েছে।",
    volume: "ভলিউম",
    currentTimeLabel: "বর্তমান সময়",
    voiceMale: "পুরুষ কণ্ঠ",
    alarmsBtn: "এলার্ম",
    fullCalendar: "পূর্ণ ক্যালেন্ডার",
    close: "বন্ধ করুন",
    ramadanDay: "রমজান",
    date: "তারিখ",
    ashra1: "রহমতের ১০ দিন",
    ashra2: "বরকতের ১০ দিন",
    ashra3: "মাগফিরাতের ১০ দিন",
    ongoing: "চলমান",
    iftarRemaining: "ইফতারের বাকি",
    suhoorRemaining: "সেহরির বাকি",
    suhoorEnded: "সেহেরী শেষ",
    iftarEnded: "ইফতার হয়েছে",
    share: "শেয়ার",
    shareMessage: "তারিখ: {date}\n{day}\nসেহরি: {suhoor}, ইফতার: {iftar}\nমসজিদ হযরত হামজা (রা:)",
    copied: "কপি হয়েছে!",
    hadith: "আবু হুরায়রা (রাঃ) থেকে বর্ণিতঃ রাসূলুল্লাহ (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম) বলেছেন, আল্লাহ তা'আলা বলেন, বনী আদমের প্রতিটি আমল তার নিজের জন্য, শুধু রোজা ব্যতীত; কারণ তা আমার জন্য এবং আমিই এর প্রতিদান দেব। নিশ্চয়ই রোজাদারের মুখের গন্ধ আল্লাহর নিকট কস্তুরীর সুগন্ধির চেয়েও অধিক প্রিয়। (সহীহ বুখারী ৫৯২৭)",
    previewSuhoor: "সেহরি ভয়েস শুনুন",
    periods: {
      dawn: "ভোর", morning: "সকাল", noon: "দুপুর", afternoon: "বিকেল", evening: "সন্ধ্যা", night: "রাত"
    },
    weekdays: {
      Monday: 'সোমবার', Tuesday: 'মঙ্গলবার', Wednesday: 'বুধবার', Thursday: 'বৃহস্পতিবার',
      Friday: 'শুক্রবার', Saturday: 'শনিবার', Sunday: 'রবিবার'
    },
    months: ["জানুয়ারি", "ফেব্রুয়ারি", "মার্চ", "এপ্রিল", "মে", "জুন জুলাই", "আগস্ট", "সেপ্টেম্বর", "অক্টোবর", "নভেম্বর", "ডিসেম্বর"]
  },
  [Language.PT]: {
    title: "Mesquita Hazrat Hamza (R.A) - Horário",
    subTitle: "Centro Cultural Muçulmano do Porto",
    suhoor: "Suhur",
    iftar: "Iftar",
    ramadanMonth: "Ramadão",
    daysRemaining: "Dias\nRestantes",
    save: "Guardar",
    cancel: "Cancelar",
    iftarAlarm: "Adhan de Iftar",
    suhoorAlarm: "Aviso de Suhur",
    today: "Hoje",
    suhoorVoiceMsg: "O tempo de Suhur terminou.",
    volume: "Volume",
    currentTimeLabel: "Hora Atual",
    voiceMale: "Voz Masculina",
    alarmsBtn: "Alarmes",
    fullCalendar: "Calendário",
    close: "Fechar",
    ramadanDay: "Dia Ramadão",
    date: "Data",
    ashra1: "10 Dias de Misericórdia",
    ashra2: "10 Dias de Bênção",
    ashra3: "10 Dias de Perdão",
    ongoing: "Em curso",
    iftarRemaining: "Para o Iftar",
    suhoorRemaining: "Para o Suhur",
    suhoorEnded: "Suhur terminou",
    iftarEnded: "Iftar passou",
    previewSuhoor: "Ouvir voz de Suhur",
    share: "Partilhar",
    shareMessage: "Data: {date}\n{day}\nSuhur: {suhoor}\nIftar: {iftar}\nMesquita Hazrat Hamza (R.A)",
    copied: "Copiado!",
    hadith: "Narrado por Abu Huraira: O Profeta disse: \"(Allah disse), 'Toda boa ação do filho de Adão é para ele, exceto o jejum; é para Mim, e Eu recompensarei (a pessoa que jejua) por isso.' Em verdade, o cheiro da boca de uma pessoa que jejua é melhor para Allah do que o cheiro do almíscar.\" (Sahih al-Bukhari 5927)",
    periods: {
      dawn: "Madrugada", morning: "Manhã", noon: "Meio-dia", afternoon: "Tarde", evening: "Noite", night: "Noite"
    },
    weekdays: {
      Monday: 'Segunda', Tuesday: 'Terça', Wednesday: 'Quarta', Thursday: 'Quinta',
      Friday: 'Sexta', Saturday: 'Sábado', Sunday: 'Domingo'
    },
    months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]
  }
};